# Bat P0.09 / P0.10 lam GPIO thuong (mac dinh la chan NFC) - dung cho LED0, LED1
CONFIG_NFCT_PINS_AS_GPIOS=y

# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Tu dong chuyen USB/BLE
CONFIG_ZMK_USB=y

# Ngu sau khi khong dung (ms) = 15 phut
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_SLEEP=y
